site_name: Go2ApiDoc
site_url: https://github.com/rickey-alok/
repo_url: https://github.com/rickey-alok/go2apidoc
repo_name: rickey-alok/go2apidoc
theme:
  # custom_dir: docs/overrides
  name: material
  language: en
  logo: https://t4.ftcdn.net/jpg/03/22/95/69/360_F_322956978_9ESBVewTYdhSu9G6qf2JazX9tUsdh53g.jpg
  favicon: https://t4.ftcdn.net/jpg/03/22/95/69/360_F_322956978_9ESBVewTYdhSu9G6qf2JazX9tUsdh53g.jpg
  font:
    text: Kalam
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    edit: material/pencil
    view: material/eye
    annotation: material/star-four-points-circle
    admonition:
      type: material/alert-box
  features:
    # - header.autohide
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.stickey
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    # - content.tabs.link
    # - content.code.annotate
    - content.code.copy
    # - content.action.view #   `view icon` to the github repo
    - content.action.edit #   `edit icon` to the github repo
  palette:
    # - scheme: red
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to system preference
extra_css:
  - stylesheets/extra.css
use_directory_urls: true
nav:
  - Home: index.md
  - API: API.md
  - Docs-as-Code:
      - VS-Code: Docs-as-Code/VS-Code.md
      - Git & GitHub: Docs-as-Code/Git-GitHub.md
      - Postman: Docs-as-Code/Postman.md
  - For writing API Docs:
      - Markdown: API Docs/Markdown.md
      - OpenAPI Specification: API Docs/OepnAPISpec.md
      - cURL: API Docs/cURL.md
      - JSON: API Docs/JSON.md
      - Miscellaneous: API Docs/Miscellaneous.md

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  # # alternate:
  #   # - name: English
  #   #   link: /en/
  #   #   lang: en
  #   # - name: Afrikaans
  #   #   link: /af/
  #   #   lang: af
  #   - analytics:
  #     provider: google
  #     property: G-0STBM9BNC1

  plugins:
    - info
    - git-authors
    - minify:
      minify_html: true
    - i18n:
      default language: en
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_search: false
      languages:
        - locale: en
          name: English
          build: true
        - locale: af
          name: Afrikaans
          build: true
    - autorefs

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: Copyright &copy; 2016-2024 Martin Donath
